export const REGISTER_COPY = {
  title: "Create an account",
  subtitle: "Enter your email and password to register.",
  emailLabel: "Email",
  emailPlaceholder: "Enter email",
  passwordLabel: "Password",
  passwordPlaceholder: "Enter password",
  confirmPasswordLabel: "Confirm password",
  confirmPasswordPlaceholder: "Confirm password",
  register: "Register",
  alreadyHaveAccount: "Already have an account?",
  signIn: "Sign in",
  needHelp: "Need help?",
  contactUs: "Contact Us",
  contactMailto: "mailto:support@bspblueprint.com",
  version: "Version 1.0",
  privacyAndTerms: "Privacy Policy  |  Terms of Use",
} as const;
